services:
  backend:
    image: jenkinsci/blueocean
    restart: on-failure
    volumes:
      - jenkins-home:/var/jenkins_home
    ports:
      - 50000:50000
      - 8080:8080 
volumes:
  jenkins-home: {}

